title: Hi CG, BRYAN LEE Here!!
description: Pursuing a Diploma in Information Technology at Temasek Polytechnic, currently in my second year.
url: https://www.linkedin.com/in/bryan-lee-204b611b3/
#show_dowloads: true
theme: jekyll-theme-minimal
