title: Hi CG, BRYAN LEE Here!!
description: Pursuing a Diploma in Information Technology at Temasek Polytechnic, currently in my second year.
LinkinProfile: /<a href="https://www.linkedin.com/in/bryan-lee-204b611b3"><img src="image.png" alt="Image Icon">Linkin</a>
#show_dowloads: true
theme: jekyll-theme-minimal
