title: Hi CG, BRYAN LEE Here!!
description: Pursuing a Diploma in Information Technology at Temasek Polytechnic, currently in my second year.
linkedinProfile: /<a href="https://www.linkedin.com/in/bryan-lee-204b611b3"><img src="https://cdn5.vectorstock.com/i/thumb-large/99/09/linkedin-social-media-icon-design-template-vector-22339909.jpg" alt="Image Icon">Linkin</a>
#show_dowloads: true
theme: jekyll-theme-minimal
